/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kz.dkgroup.cap

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class CAPPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'kz.dkgroup.cap.greeting'")
            }
        }
    }
}
