/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kz.dkgroup.CAP

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

class CAPPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("kz.dkgroup.cap.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
